baseURL: "https://js.waku.guide/"
languageCode: "en-us"
defaultContentLang: en
title: "Waku Connect Docs"
theme: "hugo-book"
enableGitInfo: true

menu:
  before: []
  after:
    - name: "JS-Waku API Doc"
      url: "https://js.waku.org/"
      weight: 5
    - name: "Vac"
      url: "https://vac.dev/"
      weight: 10
    - name: "Vac RFCs"
      url: "https://rfc.vac.dev/"
      weight: 20
    - name: "Status.im"
      url: "https://status.im/"
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: github-ascii
  tableOfContents:
    startLevel: 1

params:
  BookTheme: 'dark'
  BookToC: true
  BookSection: 'docs'
  BookDateFormat: 'Jan 2, 2006'
  BookSearch: true

  # GitHub edit links
  BookRepo: 'https://github.com/waku-org/js.waku.guide'
  BookCommitPath: 'commit'
  BookEditPath: 'edit/develop'

